# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iLost' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iLost
  pod 'AWSMobileClient', '~> 2.6.6'  # For AWSMobileClient
  pod 'AWSS3', '~> 2.6.6'            # For file transfers
  pod 'AWSCognito', '~> 2.6.6'       # For data sync
	
  target 'iLostTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iLostUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
